# Adapted from a template found at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Laravel.gitlab-ci.yml

image: php:latest

default:
  tags:
  # need this to avoid dodgy/broken comsc runners
    - general-docker

services:
  - mysql:latest

variables:
  GIT_STRATEGY: clone

cache:
  paths:
    - vendor/
    - node_modules/

before_script:
  # upgrade
  - apt-get update -y
  - apt-get upgrade -y
  # install required packages
  - apt-get install git-core -y
  - apt-get install zip unzip -y
  - apt-get install npm -y
  # install composer
  - cd laravel-moove && curl -sS https://getcomposer.org/installer | php
  # install dependencies
  - php composer.phar install
  - npm install
  # create .env.testing from example file
  - cp .env.testing.example .env.testing
  # compile assets
  - npm run dev

test:
  script:
    # run laravel tests
    - php vendor/bin/phpunit --coverage-text --colors=never tests
